name: IntegrationTest

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server -y

      - name: Start and Enable MySQL
        run: |
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sudo systemctl status mysql

      - name: Create User and Grant Access
        run: |
          sudo mysql -e "CREATE USER '${{ secrets.DB_USER}}'@'${{ secrets.DB_HOST}}' IDENTIFIED BY '${{ secrets.DB_PASSWORD}}';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO '${{ secrets.DB_USER}}'@'${{ secrets.DB_HOST}}' WITH GRANT OPTION;"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Test
        env:
          DBHost: ${{ secrets.DB_HOST}}
          DBDatabase: ${{ secrets.DBTEST_NAME}}
          DBUser: ${{ secrets.DB_USER}}
          DBPassword: ${{ secrets.DB_PASSWORD}}
        run: |
          pwd
          ls -al
          mvn clean install -DskipTests=false
