---
name: First Workflow

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    branches: 
      - 'main'

jobs:
  validate-ami-template:
    runs-on: ubuntu-latest

    steps:
      - name: first step
        run: echo "Hello World!"
