name: IntegrationTest

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Integration test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          echo "MYSQLInstalled"

      - name: Start and check MySQL
        run: |
          sudo systemctl start mysql
          sudo systemctl enable mysql
          echo "MySQLEnable"
          sudo systemctl status mysql

      - name: Build and Test
        run: |
          pwd
          ls -al
          mvn clean install
