name: Packer Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Packer Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

#      - name: Setup MySQL
#        uses: mirromutth/mysql-action@v1.1
#        with:
#          mysql database: 'hdptestapp'
#          mysql user: 'vamsi'
#          mysql password: '${{ secrets.MYSQL_PASSWORD }}'

      - name: Build
        run: |
          pwd
          ls -al
          mvn clean install -DskipTests

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Initialize and Validate Packer Template
        run: |
          cd ./packer/
          packer init packer.pkr.hcl
          packer validate packer.pkr.hcl

      - name: Format Packer Template
        run: |
          cd ./packer/
          packer fmt packer.pkr.hcl

      - name: Check for Changes
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]; then
            echo "ERROR: Running 'packer fmt' made changes to the packer.pkr.hcl file."
            exit 1
          fi    
          
          
